Repository CatalystDevOrg/Catalyst, pull requests merged in 2022-04, with the labels that each got.

#199 Data URI support
  src/search.js
Labels: enhancement, help wanted, good first issue, design, low priority

#207 Add better home page
  assets/icons/ggl.svg
  assets/icons/plus.png
  pnpm-lock.yaml
  src/home.js
  src/welcome.html
Labels: enhancement, help wanted, good first issue, design, on hold, high priority

#196 feat: Add a check to make plug-ins more secure (draft)
  src/index.html
  src/pluginCheck.js
  src/pluginWorker.js
Labels: enhancement, help wanted, optimization, design, javascript, high priority
